# Path to folder containing a round of raw OS videos and log/scheme csv files
video_set: /home/iglohut/Documents/MemDyn/OS_Data/Videos/Round7

# Path to where the h5 training set must be stored (will be huge, external storage suggested)
store_h5_path: /media/iglohut/UFDRecovery

# Size of width x height to resize ALL videos to. The network will only be able to get input from this size!
resize:
  width: 384
  height: 512



# NETWORK TRAIN RELATED #

# Data set used for training the network
dataset: /media/iglohut/MD_Smits/Internship/autoscore_3d/data/data.h5

model_params:
  # Name of main model to load/train/save
  name: nepmodel
  # Number of frames to use per nBatch x nframes x width x height x RGB input: middle frame is used as target
  n_frames: 9
  # frame apart interval: e.g. n_frames are taken,e ach n_steps apart
  n_frames_steps: 4
  # Batch size of training
  batch_size: 7
  # Percentage of data set used for training (leftover is for validation)
  train_val_split: 0.9
  # Number of epochs
  n_epochs: 10000
  # Number of iterations per epoch for training
  n_iters_train: 1
  # Number of iterations per epoch for testing
  n_iters_val: 1



behaviours:
  - Exploration
